# Generated by Django 5.2.7 on 2025-10-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.TextField()),
                ('fecha_creado', models.DateTimeField()),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministradorNegocio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=64)),
                ('contrasena', models.TextField()),
            ],
            options={
                'db_table': 'administrador_negocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
                ('fecha_vigencia', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apartado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=64)),
                ('contrasena', models.TextField()),
            ],
            options={
                'db_table': 'cajero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
            ],
            options={
                'db_table': 'canje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('sitio_web', models.TextField(blank=True, null=True)),
                ('fecha_creado', models.DateTimeField()),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_int', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'negocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('limite_por_usuario', models.IntegerField(blank=True, null=True)),
                ('limite_total', models.IntegerField(blank=True, null=True)),
                ('inicio_promocion', models.DateTimeField()),
                ('final_promocion', models.DateTimeField()),
                ('imagen', models.TextField(blank=True, null=True)),
                ('numero_canjeados', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'promocion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromocionCategoria',
            fields=[
                ('pk', models.CompositePrimaryKey('id_promocion', 'id_categoria', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'promocion_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudNegocio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'solicitud_negocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudNegocioDetalle',
            fields=[
                ('pk', models.CompositePrimaryKey('id_solicitud', 'fecha_creado', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
                ('es_aprobado', models.IntegerField()),
                ('num_intento', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud_negocio_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_negocio', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
            ],
            options={
                'db_table': 'suscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.TextField()),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_int', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_creado', models.DateTimeField()),
                ('folio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
