# Generated by Django 5.2.7 on 2025-10-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0005_alter_administradornegocio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradornegocio',
            options={},
        ),
    ]
