# Generated by Django 5.2.7 on 2025-10-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0006_alter_administradornegocio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocio',
            options={},
        ),
    ]
