# Generated by Django 5.2.7 on 2025-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0007_alter_negocio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudnegocio',
            options={},
        ),
        migrations.AlterField(
            model_name='negocio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
