# Generated by Django 5.2.7 on 2025-10-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0008_alter_solicitudnegocio_options_alter_negocio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudnegocio',
            name='id_negocio',
            field=models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio'),
        ),
        migrations.AlterField(
            model_name='solicitudnegocio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
