# Generated by Django 5.2.7 on 2025-10-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0010_alter_solicitudnegocio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudnegocio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
