# Generated by Django 5.2.7 on 2025-10-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0014_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
