# Generated by Django 5.2.7 on 2025-10-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0015_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apartado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cajero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='canje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
