# Generated by Django 5.2.7 on 2025-10-16 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.TextField()),
                ('fecha_creado', models.DateTimeField()),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('sitio_web', models.TextField(blank=True, null=True)),
                ('fecha_creado', models.DateTimeField()),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_int', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'negocio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.TextField()),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_int', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_creado', models.DateTimeField()),
                ('folio', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('colaborador', 'Colaborador'), ('administrador', 'Administrador'), ('cajero', 'Cajero'), ('usuario', 'Usuario')], default='usuario', max_length=30)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=64)),
                ('contrasena', models.TextField()),
                ('id_negocio', models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio')),
            ],
            options={
                'db_table': 'cajero',
            },
        ),
        migrations.CreateModel(
            name='AdministradorNegocio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=64)),
                ('contrasena', models.TextField()),
                ('id_negocio', models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio')),
            ],
            options={
                'db_table': 'administrador_negocio',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('limite_por_usuario', models.IntegerField(blank=True, null=True)),
                ('limite_total', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('imagen', models.TextField(blank=True, null=True)),
                ('numero_canjeados', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=5, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creado', models.DateTimeField(auto_now=True)),
                ('id_administrador_negocio', models.ForeignKey(blank=True, db_column='id_administrador_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.administradornegocio')),
                ('id_negocio', models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio')),
            ],
            options={
                'db_table': 'promocion',
            },
        ),
        migrations.CreateModel(
            name='PromocionCategoria',
            fields=[
                ('pk', models.CompositePrimaryKey('id_promocion', 'id_categoria', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.categoria')),
                ('id_promocion', models.ForeignKey(db_column='id_promocion', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.promocion')),
            ],
            options={
                'db_table': 'promocion_categoria',
            },
        ),
        migrations.CreateModel(
            name='SolicitudNegocio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=20)),
                ('id_negocio', models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio')),
            ],
            options={
                'db_table': 'solicitud_negocio',
            },
        ),
        migrations.CreateModel(
            name='SolicitudNegocioDetalle',
            fields=[
                ('pk', models.CompositePrimaryKey('id_solicitud', 'fecha_creado', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
                ('es_aprobado', models.IntegerField()),
                ('num_intento', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.administrador')),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.solicitudnegocio')),
            ],
            options={
                'db_table': 'solicitud_negocio_detalle',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_negocio', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
                ('id_negocio', models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.usuario')),
            ],
            options={
                'db_table': 'suscripcion',
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
                ('id_cajero', models.ForeignKey(db_column='id_cajero', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.cajero')),
                ('id_promocion', models.ForeignKey(db_column='id_promocion', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.promocion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.usuario')),
            ],
            options={
                'db_table': 'canje',
            },
        ),
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField()),
                ('fecha_vigencia', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('id_promocion', models.ForeignKey(db_column='id_promocion', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.promocion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.usuario')),
            ],
            options={
                'db_table': 'apartado',
            },
        ),
    ]
