# Generated by Django 5.2.7 on 2025-10-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradornegocio',
            options={},
        ),
    ]
