# Generated by Django 5.2.7 on 2025-10-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0002_alter_administradornegocio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradornegocio',
            name='id_negocio',
            field=models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio'),
        ),
    ]
