# Generated by Django 5.2.7 on 2025-10-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_alter_promocion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
