# Generated by Django 5.2.7 on 2025-10-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_administradornegocio_id_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradornegocio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
