# Generated by Django 5.2.7 on 2025-10-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0004_alter_administradornegocio_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradornegocio',
            options={'managed': False},
        ),
    ]
