# Generated by Django 5.2.7 on 2025-10-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0004_alter_promocion_imagen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitudnegociodetalle',
            unique_together={('id_solicitud', 'fecha_creado')},
        ),
        migrations.AddField(
            model_name='solicitudnegociodetalle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='solicitudnegociodetalle',
            name='pk',
        ),
    ]
