# Generated by Django 5.2.7 on 2025-10-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0005_alter_solicitudnegociodetalle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudnegociodetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
