# Generated by Django 5.2.7 on 2025-10-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0006_alter_solicitudnegociodetalle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudnegociodetalle',
            name='id',
        ),
        migrations.AddField(
            model_name='solicitudnegociodetalle',
            name='pk',
            field=models.CompositePrimaryKey('id_solicitud', 'fecha_creado', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
