# Generated by Django 5.2.7 on 2025-10-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0007_remove_solicitudnegociodetalle_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitudnegociodetalle',
            unique_together=set(),
        ),
    ]
