# Generated by Django 5.2.7 on 2025-10-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0008_alter_solicitudnegociodetalle_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
