# Generated by Django 5.2.7 on 2025-10-20 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0009_alter_codigoqr_fecha_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='id_promocion',
            field=models.ForeignKey(db_column='id_promocion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.promocion'),
            preserve_default=False,
        ),
    ]
