# Generated by Django 5.2.7 on 2025-10-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0009_solicitudnegocio_id_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudnegocio',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
