# Generated by Django 5.2.7 on 2025-10-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0010_codigoqr_id_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='utilizado',
            field=models.BooleanField(default=False),
        ),
    ]
