# Generated by Django 5.2.7 on 2025-10-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0011_alter_solicitudnegocio_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={},
        ),
    ]
