# Generated by Django 5.2.7 on 2025-10-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0011_codigoqr_utilizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudnegocio',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudnegociodetalle',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
