# Generated by Django 5.2.7 on 2025-10-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0012_alter_solicitudnegocio_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
