# Generated by Django 5.2.7 on 2025-10-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0012_alter_promocion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='final_promocion',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='promocion',
            old_name='inicio_promocion',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='promocion',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='promocion',
            old_name='monto',
            new_name='porcentaje',
        ),
        migrations.AddField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fecha_creado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='id_administrador_negocio',
            field=models.ForeignKey(blank=True, db_column='id_administrador_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.administradornegocio'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='id_negocio',
            field=models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.negocio'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='precio',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
