# Generated by Django 5.2.7 on 2025-10-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0013_alter_negocio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
