# Generated by Django 5.2.7 on 2025-10-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0013_rename_final_promocion_promocion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
