# Generated by Django 5.2.7 on 2025-10-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0014_alter_negocio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
