# Generated by Django 5.2.7 on 2025-10-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0015_alter_suscripcion_fecha_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
