# Generated by Django 5.2.7 on 2025-10-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0016_categoria_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='functionality.categoria'),
        ),
    ]
