# Generated by Django 5.2.7 on 2025-10-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0017_negocio_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='id_categoria',
        ),
    ]
