# Generated by Django 5.2.7 on 2025-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0018_remove_negocio_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='url_maps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='categorias',
            field=models.ManyToManyField(related_name='promociones', through='functionality.PromocionCategoria', to='functionality.categoria'),
        ),
    ]
