# Generated by Django 5.2.7 on 2025-10-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0019_negocio_url_maps_promocion_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartado',
            name='url',
        ),
    ]
