# Generated by Django 5.2.7 on 2025-10-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0020_remove_apartado_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartado',
            name='estatus',
            field=models.CharField(blank=True, choices=[('sin canjear', 'Sin Canjear'), ('canjeado', 'Canjeado')], null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(choices=[('precio', 'Precio'), ('porcentaje', 'Porcentaje'), ('2x1', '2x1'), ('Trae a un amigo', 'Trae a un amigo'), ('Otra', 'Otra')], max_length=20),
        ),
    ]
