# Generated by Django 5.2.7 on 2025-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0021_alter_apartado_estatus_alter_promocion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(choices=[('precio', 'Precio'), ('porcentaje', 'Porcentaje'), ('2x1', '2x1'), ('trae un amigo', 'Trae un amigo'), ('otra', 'Otra')], max_length=20),
        ),
    ]
